variables:
  GOOGLE_CLIENT_ID_PROD_CI: "$GOOGLE_CLIENT_ID_PROD"

stages:
  - test
  - build
  - deploy
  - production

testing:
  stage: test
  cache: {}
  script:
    - yarn install --ignore-engines
    - CI=true npm test -- --coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

build docker image for prod:
  stage: build
  only:
    - master
  script:
    - sh build_prod.sh

deploy to production:
  stage: production
  environment:
    name: Production
    url: https://peoadafsplehadubaaa.techasfafserito.com/
  when: manual
  only:
    - master
  script:
    - sh  deploy_production.sh
