name: CICD for remote-1

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: login to docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build docker Image
        run: docker build -t rqbabdl/micro-frontend-r1 .
      - name: Publish image to docker hub
        run: docker push rqbabdl/micro-frontend-r1:latest

  deploy:
    needs: build
    runs-on: micro-frontend
    steps:
      - name: Pull image from docker hub
        run: docker pull rqbabdl/micro-frontend-r1:latest
      - name: Delete old container
        run: docker rm -f remoteOneContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name remoteOneContainer rqbabdl/micro-frontend-r1
      
